name: Build GFWList

on:
  workflow_dispatch:
  schedule:
    - cron: "0 22 * * *"
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set variables
        run: |
          echo "RELEASE_NAME=GFWList Released on $(date +%Y%m%d%H%M)" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Checkout gfwlist2dnsmasq
        uses: actions/checkout@v5
        with:
          repository: cokebar/gfwlist2dnsmasq
          path: gfwlist2dnsmasq

      - name: Generate GFWList domains
        run: |
          cd gfwlist2dnsmasq
          chmod +x ./gfwlist2dnsmasq.sh
          ./gfwlist2dnsmasq.sh -l -o ./temp-gfwlist.txt
          cd ..

      - name: Merge gfwlist with gfwlist_ex.txt
        run: |
          mkdir publish
          cat ./gfwlist2dnsmasq/temp-gfwlist.txt | \
            perl -ne '/^((?=^.{3,255})[a-zA-Z0-9][-_a-zA-Z0-9]{0,62}(\.[a-zA-Z0-9][-_a-zA-Z0-9]{0,62})+)/ && print "$1\n"' > gfwlist.txt
          if [ -f gfwlist_ex.txt ]; then
            cat gfwlist_ex.txt >> gfwlist.txt
          fi
          sort --ignore-case -u gfwlist.txt > publish/gfw.txt

      - name: Generate sha256 hash
        run: |
          cd publish
          sha256sum gfw.txt > gfw.txt.sha256sum

      - name: Create temporary tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          TAG=release-$(date +%Y%m%d%H%M%S)
          git tag $TAG
          git push origin $TAG
          echo "RELEASE_TAG=$TAG" >> $GITHUB_ENV

      - name: Release and upload assets
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          release_name: ${{ env.RELEASE_NAME }}
          tag: ${{ env.RELEASE_TAG }}
          file_glob: true
          file: ./publish/*

      - name: Git push assets to "release" branch
        run: |
          cd publish || exit 1
          git init
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -b release
          git add .
          git commit -m "${{ env.RELEASE_NAME }}"
          git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git push -f -u origin release

      - name: Purge jsdelivr CDN
        run: |
          cd publish || exit 1
          for file in $(ls); do
            curl -i "https://purge.jsdelivr.net/gh/${{ github.repository }}@release/${file}"
          done
