name: Build GFWList

on:
  workflow_dispatch:
  schedule:
    - cron: "0 22 * * *"
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set variables
        run: |
          echo "RELEASE_NAME=GFWList Released on $(date +%Y%m%d%H%M)" >> $GITHUB_ENV
          echo "TAG_NAME=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Checkout gfwlist2dnsmasq
        uses: actions/checkout@v5
        with:
          repository: cokebar/gfwlist2dnsmasq
          path: gfwlist2dnsmasq

      - name: Generate GFWList domains
        run: |
          cd gfwlist2dnsmasq
          chmod +x ./gfwlist2dnsmasq.sh
          ./gfwlist2dnsmasq.sh -l -o ./temp-gfwlist.txt
          cd ..

      - name: Merge gfwlist with gfwlist_ex.txt
        run: |
          mkdir publish
          cat ./gfwlist2dnsmasq/temp-gfwlist.txt | \
            perl -ne '/^((?=^.{3,255})[a-zA-Z0-9][-_a-zA-Z0-9]{0,62}(\.[a-zA-Z0-9][-_a-zA-Z0-9]{0,62})+)/ && print "$1\n"' > gfwlist.txt
          if [ -f gfwlist_ex.txt ]; then
            cat gfwlist_ex.txt >> gfwlist.txt
          fi
          sort --ignore-case -u gfwlist.txt > publish/gfw.txt

      - name: Generate sha256 hash
        run: |
          cd publish
          sha256sum gfw.txt > gfw.txt.sha256sum

      - name: Release and upload assets
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          release_name: ${{ env.RELEASE_NAME }}
          tag: ${{ env.TAG_NAME }}
          file_glob: true
          file: ./publish/*
